### DISCUSSION TITLE
Macro Services For Query Layer

### DISCUSSION THREAD

**Discussion by findingrish** [hypertrace/hypertrace#194] [Show and tell]
### Context
Refer https://github.com/hypertrace/hypertrace/issues/166 

This is an attempt to compare performance of HT setup before/after Macro services for query layer
Hypertrace Data Config Service [combines entity, attribute & config]
Hypertrace Data Query Service  [combines query & gateway]

### Setup 
3 node EKS cluster, `t3.large` machine, HT deployed in dev configuration 

Deployment profiles 
Profile1 - Merged Query Services
![Profile1-MergedServices](https://user-images.githubusercontent.com/6513075/107635518-4b0af880-6c91-11eb-9cab-1f8ae93f4563.png)

Profile2 - Individual Query Services 
![Profile2-Individual-query-services](https://user-images.githubusercontent.com/6513075/107635593-64ac4000-6c91-11eb-9b43-3e4e27d99125.png)

Prometheus Operator used for monitoring, PodMonitors were added for individual services to enable custom metrics  [had to create PodMonitor for each service, try adding a monitoring label in the service deployment to just do with single PodMonitor]
Sample PodMonitor:
```
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    app: prometheus-operator-podmon-data-config
    release: prometheus-operator
  name: prometheus-operator-podmon-data-config
  namespace: hypertrace
spec:
  podMetricsEndpoints:
    - port: admin-port
  namespaceSelector:
    matchNames:
      - hypertrace
  selector:
    matchLabels:
      app: hypertrace-data-config-service
```

Query load generated using Jmeter deployed as a Job in the same namespace

#### Data
Hotrod Application was run, with automated load generation. 
Total number of Spans in the system: ~600k
Total number of Traces in the system: ~150k

#### Query
Test run details: Loop count 500, 10 concurrent users, initial delay 5 second

[queries.zip](https://github.com/hypertrace/hypertrace/files/5965184/queries.zip)

#### Profile 1 [Merged]
![data-query-service-resource](https://user-images.githubusercontent.com/6513075/107636934-6971f380-6c93-11eb-9ebb-2b9fe6f403e3.png)
![data-config-service-resource](https://user-images.githubusercontent.com/6513075/107636957-6f67d480-6c93-11eb-8af2-8a5a215f0bc6.png)
![data-query-service-network](https://user-images.githubusercontent.com/6513075/107636963-71ca2e80-6c93-11eb-8e1a-94f0b51f8476.png)
![data-config-service-network](https://user-images.githubusercontent.com/6513075/107636975-755db580-6c93-11eb-9b74-6a106963cb82.png)

**Throughput 8.4 QPS**

#### Profile  2 [Individual]
Gateway, Query [Combined mem usage 500 Mb, cpu usage negligible]
![query-service-resource](https://user-images.githubusercontent.com/6513075/107637042-8e666680-6c93-11eb-87e6-86eea2b85638.png)
![gateway-service-resource](https://user-images.githubusercontent.com/6513075/107637112-a342fa00-6c93-11eb-809d-5466dee1e58b.png)

Entity, Attribute, Config [Combined mem usage 550Mb, cpu usage negligible]
![entity-service-resource](https://user-images.githubusercontent.com/6513075/107637162-b35ad980-6c93-11eb-878a-db5815fd705e.png)
![config-service-resource](https://user-images.githubusercontent.com/6513075/107637172-b655ca00-6c93-11eb-9c4b-59a6de563b92.png)
![attribute-service-resource](https://user-images.githubusercontent.com/6513075/107637176-b786f700-6c93-11eb-9f34-06fab37268ee.png)

**Throughput 7.8 QPS**

**Note**: This QPS, is not a very accurate representation of the normal use case, this is low because the intent was to understand resource consumption of services under load 

### Conclusion
Grouping of services do not seems to degrade the performance in any ways, infact reduction of mem and cpu usage can be observed. We are also saving on network transfer cost.
