### ISSUE TITLE
Easy way to test locally built docker images with helm setup

### ISSUE THREAD

**Issue by JBAhire** [hypertrace/hypertrace#55]
As a contributor or someone who likes to tinker around people might build local images with changes and they should be able to test those images with helm setup using `test` tag.

For example,
As @ravisingal pointed out we support `tagOverride` for pinot. so, if I want to test pinot image I built locally which will be something like this `hypertrace/pinot:test` I just need to add two lines in `values.yaml` like below:

```yaml
pinot:
  image:
    repository: "hypertrace/pinot"
    tagOverride: "test"
    ....
```

Can we have similar way to test images using `tagOverride` for all the services?
